### ISSUE TITLE
Unable to resolve dependencies: berkshelf requires retryable (~> 1.3.3); ridley requires retryable (>= 2.0.0)

### ISSUE THREAD

**Issue by berndv** [berkshelf/berkshelf#1369] opened 2015-01-14 07:30 UTC
Since today `gem install berkshelf` fails with:

```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: berkshelf requires retryable (~> 1.3.3); ridley requires retryable (>= 2.0.0)
```

Seems that ridley v4.1.2 was released a few hours ago with a more strict requirement to `retryable` then v4.1.1 had. See https://github.com/RiotGames/ridley/blob/v4.1.1/ridley.gemspec and https://github.com/RiotGames/ridley/blob/v4.1.2/ridley.gemspec

**Comment by berndv** [comment] 2015-01-14 07:35
Workaround:

```
gem install ridley:4.1.1
gem install retryable:1.3.6
gem install berkshelf:3.2.2
```

**Comment by sethvargo** [comment] 2015-01-14 15:25
Hi there,

This is a duplicate of https://github.com/berkshelf/berkshelf/issues/1368. 

Best,
Seth

**Closed by sethvargo** 2015-01-14 15:25 UTC
