### ISSUE TITLE
Dependency on ruby 2.2 exists due to to open buff-extensions version pinning

### ISSUE THREAD

**Issue by EugenMayer** [berkshelf/berkshelf#1641] opened 2016-12-08 10:28 UTC
on the gem side, 2.0 is stated to be the minimum but that wont work out:

```
Fetching gem metadata from http://rubygems.org/...........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies...
Installing public_suffix 2.0.4
Installing multipart-post 2.0.0
Installing httpclient 2.8.2.4
Installing buff-extensions 2.0.0
Installing hashie 3.4.6
Installing buff-ignore 1.2.0
Installing buff-ruby_engine 1.0.0
Installing hitimes 1.2.4 with native extensions
Installing nio4r 1.2.1 with native extensions
Installing fuzzyurl 0.9.0
Installing mixlib-config 2.2.4
Installing mixlib-shellout 2.2.7
Installing erubis 2.7.0
Installing json 2.0.2 with native extensions
Installing mixlib-log 1.7.1
Installing retryable 2.0.4
Installing semverse 2.0.0
Installing cleanroom 1.0.0
Installing minitar 0.5.4
Installing molinillo 0.5.4
Installing thor 0.19.4
Using bundler 1.13.6
Installing addressable 2.5.0
Installing faraday 0.9.2
Gem::InstallError: buff-extensions requires Ruby version >= 2.2.0.
An error occurred while installing buff-extensions (2.0.0), and Bundler cannot continue.
Make sure that `gem install buff-extensions -v '2.0.0'` succeeds before bundling.
```

So we have a indirect >= 2.2.0 ruby dependency with the current https://rubygems.org/gems/berkshelf/versions/4.3.5 gem due to buff-extensions will be picked as 2.0.0 and they have ruby 2.2.0 compatibility.

Since berkshelf will be used on servers a lot, 2.2+ would be quiet a deal breaker. thus we might pin buff-extensions to 1.0.0

**Comment by thommay** [comment] 2016-12-08 13:16
We'll likely move berkshelf to 2.2 since 2.0 is EOL (and has been since February). Servers that actually need berkshelf (just CI nodes?) should use ChefDK.
I'll be closing this bug since we're working as intended.

**Closed by thommay** 2016-12-08 13:16 UTC

**Comment by EugenMayer** [comment] 2016-12-08 13:18
You define ruby 2.0 minimal in your rubygem and that does not work - and this is as intended? :)
