### ISSUE TITLE
Question about dependency resolver

### ISSUE THREAD

**Issue by kowal** [berkshelf/berkshelf#1416] opened 2015-04-09 10:38 UTC
Hi

You guys probably heard about Bundler switching his dependency resolver to **Molinillo** (https://github.com/CocoaPods/Molinillo). Rubygems are also going in that direction (https://github.com/rubygems/rubygems/pull/1189).

Do you think it would make sense to use it in Berkshelf as well? (or in https://github.com/berkshelf/solve to be precise). How can Molinillo be compared to what's Solve is doing? I'm not an expert in that area but I got a feeling that similar work is being done in Bundler/Rubygems and Berkshelf/ChefServer.

Please treat this issue more like a discussion about comparing (unifying) dependency resolution projects in Ruby community :)

thanks

**Comment by sethvargo** [comment] 2015-04-09 14:23
Hi @kowal 

The latest versions of Berkshelf bind to gecode, which is a depsolver written in C++. In the past, Berkshelf had its own depsolver, but it did not have 100% parity with the Chef Server depsolver.

This meant that cookbooks resolved locally via Berkshelf _could be different_ than what was resolved by the Chef Server at runtime. This is obviously a huge issue, since it destroys parity. As such, we are required to use the same depsolver the Chef Server uses (Gecode). So while Molinillo looks pretty cool, we cannot use it.

**Closed by sethvargo** 2015-04-09 14:23 UTC

**Comment by kowal** [comment] 2015-04-14 12:36
@sethvargo thanks for explanation.

To make things more interesting I've just found that there's another cookbook solver - Batali (http://hw-ops.com/blog/2015/03/17/batali/) and it's using yet another solver - **Grimoire** (https://github.com/spox/grimoire), created by @chrisroberts.

[This post](http://code.chrisroberts.org/blog/2015/03/13/the-magic-text-book/) explains why Grimoire was created and how it reuses some of Rubygems code.

I'm posting this here as follow-up as someone might be interested in comparing various Chef/Ruby solvers.

**Comment by reset** [comment] 2015-04-14 17:37
@kowal thanks for posting the information here. As @sethvargo mentioned, we had a straight Ruby resolver that was thrown out a bit over a year ago because the Chef Server didn't agree with the resolution graphs we were coming up with. The Chef Server was *wrong* so the rabbit hole could have been pretty damn deep. I would be careful using any resolvers that are not leveraging the same mechanism that Chef Server is (gecode) as they most likely will create solutions that the Chef Server does not agree with, especially as the graph complicates.

If the Chef Server ever moves to a different resolver we would definitely be interested in switching out Gecode.

**Comment by luckymike** [comment] 2015-04-28 00:22
@kowal Perhaps the Chef resolver should be configurable, so that individual users/orgs could use the resolver of their choice on the workstation/CI and on the client.

**Comment by kowal** [comment] 2015-04-28 09:17
I think configurable resolver might cause some difficult-to-track problems. I understand that changing resolver at this point might be really difficult (to not break backward compat.) or even impossible. However, seeing Bundler and Rubygems doing this, makes me think that maybe it's worth just comparing and identifying pros and cons of different resolvers for Chef Server.

**Comment by chrisroberts** [comment] 2015-04-28 15:02
Is there an example some where that provides instructions for reproducing this issue where the Chef Server produces an incorrect solution set?

**Comment by reset** [comment] 2015-04-28 18:19
@chrisroberts this was an issue that the Berkshelf & Chef team diagnosed and resolved a little over two years ago. If you crawl through the test suite history of history Berkshelf, Depselector, Solve, and Chef Server you'd be able to piece it back together.

The Erlang dependency solver in Chef Server, too, was thrown out because it didn't agree with the original Chef Server dependency solver. The Chef dudes had a number of complicated graphs you might still be able to get off of them which were used to identify parity.

**Comment by reset** [comment] 2015-04-28 18:21
@kowal there's no use in adding the option configurable resolver at this point because the Chef Server supports no such feature. Parity is the most important bit here.

**Comment by luckymike** [comment] 2015-04-28 18:24
@reset @kowal, My suggestion is for a configurable resolver for the Chef Client/Server. This would allow for resolver-of-choice parity. Not really a berks issue, but since the topic came up...

**Comment by reset** [comment] 2015-04-28 18:29
@luckymike if the Chef Client and Server supported that then we absolutely could switch our resolver to something else

**Comment by luckymike** [comment] 2015-04-28 18:34
:+1:

**Comment by kowal** [comment] 2015-06-11 15:23
@reset I've seen that you guys just added Molinillo support to Solve. Cool!

(https://github.com/berkshelf/solve/commit/9fc2d476d22ab9825b20db455bd75bbceaf6a185#diff-04c6e90faac2675aa89e2176d2eec7d8)
