### ISSUE TITLE
metadata.rb "depends" doesn't work, but "cookbook" in Berksfile does

### ISSUE THREAD

**Issue by wolftrouble** [berkshelf/berkshelf#1728] opened 2017-08-21 03:16 UTC
Apologies if I'm missing something obvious. This is a cookbook I'm trying to do some development on and I'm getting stuck on what should be a drop-dead simple thing.

Versions involved:
```
$ berks --version
6.3.0
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

Given the following Berksfile:
```
source "https://api.berkshelf.com"

metadata

group :testing do
  cookbook "apt", "~> 2.4"
end
```
And the following metadata.rb:
```
name             'apache_zookeeper'
maintainer       'Bryan Baugher'
maintainer_email 'Bryan.Baugher@Cerner.com'
license          'MIT'
description      'Installs/Configures Apache Zookeeper'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url       'https://github.com/bbaugher/apache_zookeeper/issues'
source_url       'https://github.com/bbaugher/apache_zookeeper'
chef_version     '>= 12.5'

depends "java"
depends "ulimit"

%w{ ubuntu centos }.each do |os|
  supports os
end

version          '1.3.0'
```
And a completely empty ~/.berkshelf/cookbooks, and no Berksfile.lock, this is what I see:
```
$ berks install

Resolving cookbook dependencies...
Fetching 'apache_zookeeper' from source at .
Fetching cookbook index from https://api.berkshelf.com...
Using apache_zookeeper (1.3.0) from source at .
Installing apt (2.9.2) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io:443/api/v1)
Installing ulimit (0.4.0) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io:443/api/v1)
```
Note no "java" or "ulimit". Trying to use "berks list -d" yields:
```
$ berks list -d

I, [2017-08-20T20:05:04.065709 #5519]  INFO -- : Checking if lockfile is trusted
D, [2017-08-20T20:05:04.065856 #5519] DEBUG -- : Checking apache_zookeeper (>= 0.0.0)
D, [2017-08-20T20:05:04.066685 #5519] DEBUG -- : Using 'chefignore' at '/Users/bthomas/repos/apache_zookeeper/chefignore'
D, [2017-08-20T20:05:04.074360 #5519] DEBUG -- :   Detected there is a cached cookbook
D, [2017-08-20T20:05:04.074556 #5519] DEBUG -- :   Checking transitive dependencies for apache_zookeeper (1.3.0)
D, [2017-08-20T20:05:04.074580 #5519] DEBUG -- :     Checking java (>= 0.0.0)
D, [2017-08-20T20:05:04.074594 #5519] DEBUG -- :     Not graphed - cannot be satisifed
D, [2017-08-20T20:05:04.074604 #5519] DEBUG -- :   Transitive dependencies not satisfies - cannot be trusted!
The lockfile is out of sync! Run `berks install` to sync the lockfile.
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.0/lib/berkshelf/berksfile.rb:751:in `validate_lockfile_trusted!'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.0/lib/berkshelf/berksfile.rb:483:in `list'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.0/lib/berkshelf/cli.rb:299:in `list'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.0/lib/berkshelf/cli.rb:49:in `dispatch'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.0/lib/berkshelf/cli.rb:25:in `execute!'
	/Users/bthomas/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.0/bin/berks:5:in `<top (required)>'
	/Users/bthomas/.rbenv/versions/2.4.1/bin/berks:22:in `load'
	/Users/bthomas/.rbenv/versions/2.4.1/bin/berks:22:in `<main>'
```
Okay, java isn't graphed, but if I modify my Berksfile to include java and ulimit explicitly (and make no changes to  metadata.rb):
```
source "https://api.berkshelf.com"

metadata
cookbook 'java'
cookbook 'ulimit'

group :testing do
  cookbook "apt", "~> 2.4"
end
```
And I try again:
```
$ berks install
Resolving cookbook dependencies...
Fetching 'apache_zookeeper' from source at .
Fetching cookbook index from https://api.berkshelf.com...
Using apache_zookeeper (1.3.0) from source at .
Using apt (2.9.2)
Installing java (1.50.0) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io:443/api/v1)
Using ulimit (0.4.0)
```
They install properly. And now berks list works as expected:
```
$ berks list
Cookbooks installed by your Berksfile:
  * apache_zookeeper (1.3.0) from source at .
  * apt (2.9.2)
  * java (1.50.0)
  * ulimit (0.4.0)
```
What's going wrong? The use of "metadata" in Berksfile seems very straightforward so I'm confused.

**Comment by redterror** [comment] 2017-08-21 04:23
Oh good, I thought I was going insane.  I think I have the same problem.  In my case it manifested as @wolftrouble described but I also see this behavior which I think is related:

```
$ ls
Berksfile  Berksfile.lock  chefignore  metadata.rb  README.md  recipes/
$ rm -rf Berksfile.lock ~/.berkshelf/cookbooks
$ berks --version
6.3.0
$ cat metadata.rb
name             'woop-base'
maintainer       'XXX'
maintainer_email 'XXX'
license          'All rights reserved'
description      'Installs/Configures woop-base'
long_description 'Installs/Configures woop-base'
version          '0.1.0'

depends 'ntp'
depends 'sudo'
depends 'users'
$ cat Berksfile
source "https://api.berkshelf.com"

metadata
$ berks install
Resolving cookbook dependencies...
Fetching 'woop-base' from source at .
Fetching cookbook index from https://api.berkshelf.com...
Using woop-base (0.1.0) from source at .
Installing users (5.1.0) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io:443/api/v1)
$ berks list
The lockfile is out of sync! Run `berks install` to sync the lockfile.
$ cat Berksfile.lock
DEPENDENCIES
  woop-base
    path: .
    metadata: true

GRAPH
  users (5.1.0)
  woop-base (0.1.0)
    ntp (>= 0.0.0)
    sudo (>= 0.0.0)
    users (>= 0.0.0)
$ berks install --debug
I, [2017-08-21T04:18:21.837853 #4683]  INFO -- : Reducing lockfile
D, [2017-08-21T04:18:21.838046 #4683] DEBUG -- : Current lockfile:
D, [2017-08-21T04:18:21.838101 #4683] DEBUG -- :
D, [2017-08-21T04:18:21.838447 #4683] DEBUG -- :   DEPENDENCIES
D, [2017-08-21T04:18:21.838501 #4683] DEBUG -- :     woop-base
D, [2017-08-21T04:18:21.838551 #4683] DEBUG -- :       path: .
D, [2017-08-21T04:18:21.838587 #4683] DEBUG -- :       metadata: true
D, [2017-08-21T04:18:21.838630 #4683] DEBUG -- :
D, [2017-08-21T04:18:21.838682 #4683] DEBUG -- :   GRAPH
D, [2017-08-21T04:18:21.838728 #4683] DEBUG -- :     users (5.1.0)
D, [2017-08-21T04:18:21.838772 #4683] DEBUG -- :     woop-base (0.1.0)
D, [2017-08-21T04:18:21.838822 #4683] DEBUG -- :       ntp (>= 0.0.0)
D, [2017-08-21T04:18:21.838865 #4683] DEBUG -- :       sudo (>= 0.0.0)
D, [2017-08-21T04:18:21.838917 #4683] DEBUG -- :       users (>= 0.0.0)
D, [2017-08-21T04:18:21.838959 #4683] DEBUG -- :
D, [2017-08-21T04:18:21.839004 #4683] DEBUG -- : Unlocking dependencies no longer in the Berksfile
D, [2017-08-21T04:18:21.839080 #4683] DEBUG -- :   Checking woop-base (0.1.0)
D, [2017-08-21T04:18:21.839142 #4683] DEBUG -- :     Skipping unlock for woop-base (exists in the Berksfile)
D, [2017-08-21T04:18:21.839186 #4683] DEBUG -- : Removing transitive dependencies
D, [2017-08-21T04:18:21.839238 #4683] DEBUG -- :   Checking woop-base (>= 0.0.0)
D, [2017-08-21T04:18:21.840340 #4683] DEBUG -- : Using 'chefignore' at '/home/dave_gbcx/dev/woop-chef/cookbooks/woop-base/chefignore'
D, [2017-08-21T04:18:21.844865 #4683] DEBUG -- :     Cached cookbook exists
D, [2017-08-21T04:18:21.844953 #4683] DEBUG -- :     Updating cookbook dependencies if required
D, [2017-08-21T04:18:21.845125 #4683] DEBUG -- : New lockfile:
D, [2017-08-21T04:18:21.845177 #4683] DEBUG -- :
D, [2017-08-21T04:18:21.845283 #4683] DEBUG -- :   DEPENDENCIES
D, [2017-08-21T04:18:21.845341 #4683] DEBUG -- :     woop-base
D, [2017-08-21T04:18:21.845388 #4683] DEBUG -- :       path: .
D, [2017-08-21T04:18:21.845428 #4683] DEBUG -- :       metadata: true
D, [2017-08-21T04:18:21.845471 #4683] DEBUG -- :
D, [2017-08-21T04:18:21.845553 #4683] DEBUG -- :   GRAPH
D, [2017-08-21T04:18:21.845596 #4683] DEBUG -- :     users (5.1.0)
D, [2017-08-21T04:18:21.845641 #4683] DEBUG -- :     woop-base (0.1.0)
D, [2017-08-21T04:18:21.845682 #4683] DEBUG -- :       ntp (>= 0.0.0)
D, [2017-08-21T04:18:21.845723 #4683] DEBUG -- :       sudo (>= 0.0.0)
D, [2017-08-21T04:18:21.845764 #4683] DEBUG -- :       users (>= 0.0.0)
D, [2017-08-21T04:18:21.845810 #4683] DEBUG -- :
Resolving cookbook dependencies...
I, [2017-08-21T04:18:21.845934 #4683]  INFO -- : Checking if lockfile is trusted
D, [2017-08-21T04:18:21.845992 #4683] DEBUG -- : Checking woop-base (0.1.0)
D, [2017-08-21T04:18:21.849134 #4683] DEBUG -- : Using 'chefignore' at '/home/dave_gbcx/dev/woop-chef/cookbooks/woop-base/chefignore'
D, [2017-08-21T04:18:21.852930 #4683] DEBUG -- :   Detected there is a cached cookbook
D, [2017-08-21T04:18:21.853283 #4683] DEBUG -- :   Checking transitive dependencies for woop-base (0.1.0)
D, [2017-08-21T04:18:21.853345 #4683] DEBUG -- :     Checking ntp (>= 0.0.0)
D, [2017-08-21T04:18:21.853433 #4683] DEBUG -- :     Not graphed - cannot be satisifed
D, [2017-08-21T04:18:21.853483 #4683] DEBUG -- :   Transitive dependencies not satisfies - cannot be trusted!
I, [2017-08-21T04:18:21.853545 #4683]  INFO -- : Installing from universe
Fetching 'woop-base' from source at .
D, [2017-08-21T04:18:21.854592 #4683] DEBUG -- : Using 'chefignore' at '/home/dave_gbcx/dev/woop-chef/cookbooks/woop-base/chefignore'
D, [2017-08-21T04:18:21.858453 #4683] DEBUG -- :   Creating a resolver
Fetching cookbook index from https://api.berkshelf.com...
D, [2017-08-21T04:18:23.866881 #4683] DEBUG -- :   Adding explicit dependency on woop-base (0.1.0) '/home/dave_gbcx/dev/woop-chef/cookbooks/woop-base'
D, [2017-08-21T04:18:23.867366 #4683] DEBUG -- :   Starting resolution...
I, [2017-08-21T04:18:25.498263 #4683]  INFO -- : Installing users (5.1.0)
D, [2017-08-21T04:18:25.498907 #4683] DEBUG -- :   Already installed - skipping install
Using users (5.1.0)
I, [2017-08-21T04:18:25.499298 #4683]  INFO -- : Installing woop-base (0.1.0)
D, [2017-08-21T04:18:25.499482 #4683] DEBUG -- :   Already installed - skipping install
Using woop-base (0.1.0) from source at .
D, [2017-08-21T04:18:25.499714 #4683] DEBUG -- :   Finished resolving, calculating locks
D, [2017-08-21T04:18:25.499912 #4683] DEBUG -- :   New locks
D, [2017-08-21T04:18:25.499987 #4683] DEBUG -- :     woop-base (0.1.0)
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

It looks like the graph gets constructed correctly, but then later when it goes to install

**Comment by thommay** [comment] 2017-08-21 11:19
This is probably a dup of #1723 , which should be fixed in the next release.

**Comment by thommay** [comment] 2017-08-21 11:19
Duplicate of #1723

**Comment by redterror** [comment] 2017-08-21 12:54
Thanks for that, using berkshelf from master appears to resolve it.

**Comment by thommay** [comment] 2017-08-21 13:25
Great, thanks for the confirmation!

**Comment by wolftrouble** [comment] 2017-08-21 15:10
Thanks!

**Comment by lamont-granquist** [comment] 2017-08-21 17:31
yeah closing this as a dup, it is just the molinillo/solve issue.  should be handled by bumping both of those in your Gemfile/Gemfile.lock or using latest chef-dk.

**Closed by lamont-granquist** 2017-08-21 17:31 UTC
