### ISSUE TITLE
berkshelf >=4.1.0 yielding 'circular dependency' error

### ISSUE THREAD

**Issue by babbottscott** [berkshelf/berkshelf#1534] opened 2016-03-11 18:07 UTC
My understanding of the chef metadata 'depends' directive may cloud my report here.

Scenario: cookbook A (v1.0.0) 'depends' on cookbook B (~> 2.0.0) for a useful recipe.  cookbook B (v2.0.0) 'depends' on cookbook A (~> 1.0.0) for a useful library function (or lwrp).

Berkshelf < 4.1 resolves the dependencies successfully.  Berkshelf >= 4.1.0 declares a circular dependency error with molinillo solver.  With gecode solver and dep-selector-libgecode 1.1.0, we're hitting timeouts, but with an increased SOLVE_TIMEOUT it succeeds. 

Is there a chef change that precipitated this change to dependency calculation?  Is circular dependency actually a problem, given the compile phase of chef-client (i.e. shouldn't availability of the depended-on cookbook/version be sufficient to break the cycle)?

**Comment by mfischer-zd** [comment] 2016-03-12 20:52
I'm seeing erroneous circular-dependency errors even where the cookbooks have no explicit circular dependency.  Without the ability to see Berkshelf's graph, it's difficult to see where the error is.

**Comment by elitechance** [comment] 2016-03-21 17:25
I encounter this issue using while using chef + kitchen + berkshelf.  One solution is to upgrade your ruby version.  I was using 2.0.0 and I upgraded to 2.1.8 through rbenv.  I reinstalled all needed gems of my project and everything works after that.

**Comment by xeron** [comment] 2016-03-21 18:59
@elitechance It has nothing to do with ruby version. You are probably just using berkshelf < 4.1.

I see this issue with ruby 2.3.0 and the latest berkshelf.

**Comment by elitechance** [comment] 2016-03-21 19:05
@xeron I'm currently using ruby 2.1.8 and Berkshelf 4.2.1

**Comment by xeron** [comment] 2016-03-22 18:41
```
$ berks install
Resolving cookbook dependencies...
Fetching 'cookbook1' from source at .
Fetching cookbook index from https://berkshelf.corp.example.com...
There is a circular dependency between cookbook2 and cookbook3
Unable to find a solution for demands: cookbook1 (0.3.0)
```

Versions:
```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ berks -v
4.3.0
$ gem list | grep solve
solve (2.0.3)
$ gem list | grep gecode
dep-selector-libgecode (1.2.0)
```

**Comment by xeron** [comment] 2016-03-22 19:29
Following configuration resolves this dependencies successfully:

```
$ berks -v
4.0.1
$ gem list | grep berkshelf-api-client
berkshelf-api-client (2.0.0)
$ gem list | grep solve
solve (2.0.3, 1.2.1)
$ gem list | grep selector
dep-selector-libgecode (1.2.0)
dep_selector (1.0.3)
```

**Comment by dancingfrog** [comment] 2016-04-04 16:56
Yep, @xeron, I can confirm that rolling back to berkshelf 4.0.1 makes the "`There is a circular dependency between ... and ...`" message go away. Will this be resolved in a near future release for berkshelf?

**Comment by pelletiermaxime** [comment] 2016-04-29 17:42
This is a major problem for me. I'm freezing Berkshelf to 4.0.1 in my Gemfiles while waiting for a fix.

**Comment by robertlabrie** [comment] 2016-05-12 16:28
Thanks to this thread, the issue is resolved for me as well using 4.0.1. I'm wondering if there is a path to resolving this?

**Comment by robertlabrie** [comment] 2016-05-12 16:55
@xeron I can confirm the same as @elitechance I do not get the circular dependency error when using berksshelf 4.2.1

**Comment by hinesmr** [comment] 2016-05-20 21:58
This bug affects me to. Reverting back to 4.0.1 solved the problem. Had to do `sudo gem install berkshelf -v 4.0.1` to solve the problem.

**Comment by tomwganem** [comment] 2016-06-07 20:02
+1 Unable to use chefdk because of this.

**Comment by elitechance** [comment] 2016-06-07 20:58
@tomwganem 
Can you try Berkshelf 4.2.1?  It works for me and @robertlabrie

**Comment by tomwganem** [comment] 2016-06-07 21:39
@elitechance 4.2.1 does not work, but 4.0.1 does.

**Comment by sds** [comment] 2016-06-08 16:55
We were able to work around this by ensuring the `dep-selector` gem was installed/bundled and including:

```ruby
solver :gecode, :required
```

...in our `Berksfile`.

We have explicitly specified `berkshelf` 4.3.3 and `dep-selector` 1.0.3 in our `Gemfile`.

**Comment by tomwganem** [comment] 2016-06-08 18:05
what @sds described worked for me.

**Comment by lamont-granquist** [comment] 2016-11-28 21:54
per https://github.com/CocoaPods/Molinillo/issues/13#issuecomment-63873092

"It is an explicit design goal of Molinillo to disallow circular dependencies."

So this is not fixable anywhere in the berkshelf code.  The only workaround is to use gecode instead of molinillo.

**Closed by lamont-granquist** 2016-11-28 21:54 UTC
Labels: Bug, High Priority
