### ISSUE TITLE
Unable to activate berkshelf-hg-0.1.0, because berkshelf-4.0.1 conflicts with berkshelf (~> 3.1)>

### ISSUE THREAD

**Issue by albeekj** [berkshelf/berkshelf#1480] opened 2015-11-14 21:48 UTC
I am trying to use the plugin berkshelf-hg and running into an issue with conflicting gems.  Any help would be much appricied 

========================================================================================================================================================================================================
#<Gem::ConflictError: Unable to activate berkshelf-hg-0.1.0, because berkshelf-4.0.1 conflicts with berkshelf (~> 3.1)>
Resolving cookbook dependencies...
Fetching 'esdk-sync' from source at .
Fetching cookbook index from https://api.berkshelf.com...
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/installer.rb:27:in `join': No live threads left. Deadlock? (fatal)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/installer.rb:27:in `map'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/installer.rb:27:in `build_universe'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/installer.rb:131:in `install_from_lockfile'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/installer.rb:37:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/berksfile.rb:380:in `install'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/berksfile.rb:589:in `block in vendor'
        from C:/opscode/chefdk/embedded/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/berksfile.rb:587:in `vendor'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:387:in `vendor'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:52:in `dispatch'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/cli.rb:27:in `execute!'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/bin/berks:5:in `<top (required)>'
        from C:/opscode/chefdk/bin/berks:42:in `load'
        from C:/opscode/chefdk/bin/berks:42:in `<main>'

....

e:\sandbox>chef gem uninstall berkshelf --version 4.0.1
Successfully uninstalled berkshelf-4.0.1

e:\sandbox>C:\opscode\chefdk\bin\/berks.BAT vendor C:/Users/cain/.berkshelf/vagrant-berkshelf/shelves/berkshelf20151113-6080-sc2dl9-esdk_sync --berksfile E:\repos\academy_mortgage\site-cookbooks\esdk-sync\Berksfile
C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'berkshelf' (= 4.0.1) - did find: [berkshelf-3.3.0] (Gem::LoadError)
Checked in 'GEM_PATH=C:/Users/cain/AppData/Local/chefdk/gem/ruby/2.1.0;C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0', execute `gem env` for more information
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from C:/opscode/chefdk/bin/berks:37:in `<main>'

e:\sandbox>chef gem install berkshelf --version 3.2.4
Fetching: berkshelf-3.2.4.gem (100%)
WARNING:  You don't have c:\users\cain\appdata\local\chefdk\gem\ruby\2.1.0\bin in your PATH,
          gem executables will not run.
Successfully installed berkshelf-3.2.4
Parsing documentation for berkshelf-3.2.4
Installing ri documentation for berkshelf-3.2.4
Done installing documentation for berkshelf after 2 seconds
1 gem installed

e:\sandbox>C:\opscode\chefdk\bin\/berks.BAT vendor C:/Users/cain/.berkshelf/vagrant-berkshelf/shelves/berkshelf20151113-6080-sc2dl9-esdk_sync --berksfile E:\repos\academy_mortgage\site-cookbooks\esdk-sync\Berksfile
C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'berkshelf' (= 4.0.1) - did find: [berkshelf-3.3.0,berkshelf-3.2.4] (Gem::LoadError)
Checked in 'GEM_PATH=C:/Users/cain/AppData/Local/chefdk/gem/ruby/2.1.0;C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0', execute `gem env` for more information
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from C:/opscode/chefdk/bin/berks:37:in `<main>'

e:\sandbox>vagrant provision
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.

**Comment by kitsemets** [comment] 2016-01-14 14:51
+1

**Comment by reset** [comment] 2016-01-15 00:33
Closing as this is a dupe of https://github.com/berkshelf/berkshelf-hg/issues/6

**Closed by reset** 2016-01-15 00:33 UTC

**Comment by albeekj** [comment] 2016-01-15 18:10
It would seem this was closed because it was a duplicate of berkshelf/berkshelf-hg#6 but  berkshelf/berkshelf-hg#6 was closed because it was a dupe up this, can we open one of them and solve it?  I don't care which
