### ISSUE TITLE
berks vendor fails with dependent Berksfile

### ISSUE THREAD

**Issue by daften** [berkshelf/berkshelf#1428] opened 2015-06-03 15:39 UTC
When I issue berks vendor from a cookbook with a Berksfile, it does not take the Berksfile from a dependent cookbook into account it seems. Is that correct behaviour?

**Comment by sethvargo** [comment] 2015-06-03 15:50
Duplicate of https://github.com/berkshelf/berkshelf/pull/304

**Closed by sethvargo** 2015-06-03 15:50 UTC
