### ISSUE TITLE
Ridley::Client#url_prefix message during berks upload

### ISSUE THREAD

**Issue by binlialfie** [berkshelf/berkshelf#1750] opened 2018-03-22 09:33 UTC
though the [previous ticket](https://github.com/berkshelf/berkshelf/issues/1716#issuecomment-336688738) is closed, after upgrade chefdk, i am still having the same warning with `berks upload`:

berks upload --force
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:271:in `server_url': Ridley::Client#url_prefix at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ridley-5.1.1/lib/ridley/client.rb:79 forwarding to private method Celluloid::PoolManager#url_prefix
Uploaded apt (6.1.4) to: 'https://api.chef.io:443/organizations/xxxxxxx

chef -v
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21

**Comment by thommay** [comment] 2018-03-22 09:37
Thanks for submitting a bug report. However, the statement at the end of the last ticket is still true - we'll release the fix once it's had sufficient testing, which we're targetting for ChefDK 3 at the end of April.

**Comment by thommay** [comment] 2018-03-22 09:37
Duplicate of #1716

**Closed by thommay** 2018-03-22 09:37 UTC
