### ISSUE TITLE
could not resolve dependancy - 3.2.2 (and 3.2.1 and 3.1.5)

### ISSUE THREAD

**Issue by prometheanfire** [berkshelf/berkshelf#1356] opened 2014-12-18 22:03 UTC
This bug seems to be hit when trying to load or parse a local metadata file, though that's not for sure.

I am testing by running 'berks' in a directory that contains phpstack ( https://github.com/rackspace-cookbooks/phpstack/releases/tag/v3.0.23 ).  In order to simplify the bug I removed a few things.

Here is the patch for the removal of extra depends an the like. https://gist.githubusercontent.com/anonymous/a4f18325a45f598418ef/raw/6a67ee5159decd7d4ad19064bd6021c759deb8b0/stdin

Here is the debug log for 3.2.2 https://gist.github.com/3e435213ac1f5003a847

**Comment by mconigliaro** [comment] 2015-01-22 21:18
We've been having resolution problems like this for over a year, but we haven't been able to track down exactly what's causing it, and are thus unable to create a bug report. What I can confirm is that berkshelf does seem to be looking at cookbook versions it shouldn't be. For example, even with a constraint on `foo` like `~> 1.0`, it still seems to be looking at versions that don't match that constraint (e.g `0.x`), and the reason I think this is because we've seen instances where deleting really old versions that are **outside** our constraints inexplicably makes resolution succeed again.

**Comment by danielsdeleo** [comment] 2015-01-26 18:06
I patched dep-selector to more aggressively trim package versions, the patch is a bit dirty and needs more cleanup before it can be merged, but if you suspect that this would improve performance for you, can you try this branch and see if it helps you? https://github.com/chef/dep-selector/pull/34

**Comment by martinb3** [comment] 2015-01-26 18:18
I'm also noticing another case where Berkshelf sees the same version locally and remotely, and chooses the remote one over the local one for dependency resolution. `berks install` fails for https://github.com/rackspace-cookbooks/platformstack/pull/177 unless I bump the version, because the remote version has unsatisfied dependencies that I'm removing anyway as part of the PR.

**Comment by mconigliaro** [comment] 2015-01-26 18:20
Yup @martinb3, we've seen the same thing.

**Comment by martinisoft** [comment] 2015-09-02 17:27
We're seeing a similar problem with one of our wrapper cookbooks. From the debug output it's stopping dead in it's tracks just past loading chefignore files from local dependencies. Don't see anything past that. Need to `kill -9` the berks process as it stops responding to TERM signals. Have tried to blow away the lockfile and do a fresh install. Only thing that does get it to work normally is renaming the wrapper cookbook name in the metadata to something else, which is peculiar.

**Comment by carpnick** [comment] 2015-10-06 13:46
We are hitting this as well.  I tried applied @danielsdeleo patch from his PR - but we didnt see any measureable improvement.  With that said we are hitting this with [this](https://gist.github.com/carpnick/485e2bf95137dfd8484d) resolved berksfile.lock and [this universe.json](https://gist.github.com/carpnick/642f55fbfda372cc79b2)

For now it is an acceptable workaround to increase `SOLVE_TIMEOUT` in the short term.  What we are a bit worried about, is our versions available will continue to grow and make this problem worse.  So far our plans are to:
* look into yanking versions we no longer want to support
* Add this workaround to our common rake tasks that call berks so internal customers dont see this
* Potentially flatten our cookbook dependency design


Pre Patch:
```
ea4ae6d2-6250-4876-b5a7-68190114eb3f: dep_selector solve: SOLVED 50 packages, 620 constraints, Time: 84739ms Stats: 1 steps, 2381678 bytes, 859245106
props, 1243734 nodes, 86 depth
```

POST patch:
```
25b36816-d2b6-4182-ae2e-a25654bd6aa1: dep_selector solve: SOLVED 50 packages, 620 constraints, Time: 87783ms Stats: 1 steps, 2381678 bytes, 859245106
props, 1243734 nodes, 86 depth
```

**Comment by daften** [comment] 2016-11-01 17:38
I seem to have the same or a similar issue. I've made a chef-repo with a Berksfile with a local cookbook (only the necessary files: readme, metadata, berksfile). This fails when issuing a berks install in the chef-repo.
[chef-repo.zip](https://github.com/berkshelf/berkshelf/files/564623/chef-repo.zip)

**Comment by lamont-granquist** [comment] 2016-11-28 21:24
The vast majority of this thread isn't actionable, has a truly horrible title, and clearly nobody is reading this anymore.  I'm going to open a separate issue for the chef-repo in the prior comment which actually is actionable.

**Closed by lamont-granquist** 2016-11-28 21:24 UTC
