### ISSUE TITLE
Berks unable to solve dependencies using open constraint in metadata

### ISSUE THREAD

**Issue by artyom-bilun** [berkshelf/berkshelf#1723] opened 2017-08-07 08:24 UTC
Hi, I'm using following `Berksfile` and `metadata.rb` files:

`Berksfile`:
```
# frozen_string_literal: true

source 'https://supermarket.local.domain'
source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook 'e3s-rabbitmq-test', path: 'test/fixtures/cookbooks/e3s-rabbitmq-test'
  cookbook 'e3s-rabbitmq-spec', path: 'test/fixtures/cookbooks/e3s-rabbitmq-spec'
end
```
`metadata.rb`:
```
# frozen_string_literal: true

name             'e3s-rabbitmq'
...
version          '3.1.3'

depends 'rabbitmq'
depends 'e3s-collectd'  # pay attention to this line
depends 'e3s-logstash'

chef_version '>= 12.12'
...
```
So, here is the `berks install` command output:
```
$ rm Berksfile.lock
$ berks install
Resolving cookbook dependencies...
Fetching 'e3s-rabbitmq' from source at .
Fetching 'e3s-rabbitmq-spec' from source at test/fixtures/cookbooks/e3s-rabbitmq-spec
Fetching 'e3s-rabbitmq-test' from source at test/fixtures/cookbooks/e3s-rabbitmq-test
Fetching cookbook index from https://supermarket.chef.io...
Fetching cookbook index from https://supermarket.local.domain...
Using apt (6.1.3)
Using e3s-logstash (3.6.5)
Using e3s-rabbitmq (3.1.3) from source at .
Using e3s-java (4.2.0)
Using ark (3.1.0)
Using e3s-rabbitmq-spec (0.1.0) from source at test/fixtures/cookbooks/e3s-rabbitmq-spec
Using e3s-rabbitmq-test (0.1.0) from source at test/fixtures/cookbooks/e3s-rabbitmq-test
Using ohai (5.1.0)
Using packagecloud (0.3.0)
Using runit (3.0.5)
Using seven_zip (2.0.2)
Using simple-logstash (0.5.1)
Using windows (3.1.1)
```
And there is no mention of 'e3s-collectd' cookbook while it exists in the local.domain supermarket.
But if I specify whatever constraint for 'e3s-collectd' cookbook in `metadata.rb`, berks successfully solves dependencies.
`metadata.rb`
```
# frozen_string_literal: true

name             'e3s-rabbitmq'
...
depends 'e3s-collectd', '~> 1.8.3'
..
```
```
$ rm Berksfile.lock
$ berks install
...
Using apt (6.1.3)
Installing e3s-collectd (1.8.3) from https://supermarket.local.domain ([opscode] https://supermarket.local.domain:443/api/v1)
Installing collectd-lib (3.1.0)
...
```
UPD: The same result using 6.1.1 and 6.2.2 versions of berkshelf

**Comment by mawatech** [comment] 2017-08-07 09:25
I had the same problem, seems that the ruby resolver has some problems. Works for me after

`gem install dep_selector`

See https://docs.chef.io/berkshelf.html#solver-keyword

**Comment by thommay** [comment] 2017-08-07 09:42
@mawatech the `gecode` solver is the default, so while your statement is completely correct - and is being tracked at berkshelf/solve#67 - this doesn't look to be the same problem.

@artyom-bilun can you confirm that you're not setting the solver? What (if any) are the dependencies that e3s-collectd expresses?

**Comment by artyom-bilun** [comment] 2017-08-07 10:04
@mawatech, thx, it works for me. Unfortunately, I did not know about the possibility of using different dependency solvers.
@thommay, I figured out that berkshelf is using implicit dependency on dep_selector. gecode solver is only used by default if dep_selector gem is installed, but there is no explicit dependency in the berkshelf itself, so, as for me, gecode isn't the default mechanism for resolving dependencies in berkshelf.

**Comment by thommay** [comment] 2017-08-07 10:12
@artyom-bilun ah, you're not using ChefDK?

**Comment by thommay** [comment] 2017-08-07 10:13
Duplicate of berkshelf/solve#67

**Comment by artyom-bilun** [comment] 2017-08-07 10:31
@thommay, no, I prefer using rvm environment over using ChefDK

**Comment by lamont-granquist** [comment] 2017-08-08 18:18
downgrade molinillo to 0.5.x until solve gets updated to work with 0.6.x or else use gecode/install dep_selector.

chef-dk 2.1.4 in the current channel also has molinillo pinned to 0.5.x for now.

**Comment by lamont-granquist** [comment] 2017-08-08 20:22
locking to avoid 'me toos' burying the workaround solution there ^

**Comment by thommay** [comment] 2017-08-11 10:11
OK, upgrading to solve 4.0.0 should resolve this correctly.

**Closed by thommay** 2017-08-11 10:11 UTC
