### ISSUE TITLE
Local cookbooks should take precedence over Supermarket when resolving dependencies

### ISSUE THREAD

**Issue by joestump** [berkshelf/berkshelf#1639] opened 2016-12-06 19:38 UTC
I've got a local cookbook named `nginx` and have added the following to my Berksfile:

```ruby
cookbook "nginx", path: "./cookbooks/nginx"
```

My local `nginx` cookbook has the version of 2.0.5. 

However, when I run it with `DEBUG_RESOLVER` I find the following in the output:

```
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (>= 0.0.0) (49 remaining)
Attempting to activate nginx-2.7.6
Found existing spec (nginx-2.4.2)
Creating possibility state for nginx (= 2.0.5) (1 remaining)
Attempting to activate nginx-2.0.5
Found existing spec (nginx-2.4.2)
```

It appears Berkshelf is ignoring the local recipe in favor of Supermarket. Is there a way to tell Berkshelf, "Please don't try and figure out dependencies from a cookbook I'm not actually using."?

**Comment by lamont-granquist** [comment] 2016-12-08 19:31
FWIW, I'm fairly certain that the PolicyFile.rb resolver does this correctly.

**Comment by joestump** [comment] 2016-12-13 17:52
@lamont-granquist it is _most_ unhelpful to hear from Chef that a core component of their developer kit is, effectively, no longer supported. Is there any kind of migration path?

**Comment by lamont-granquist** [comment] 2016-12-13 18:52
I didn't say that, if it was unsupported I would have closed this bug.

**Comment by chewi** [comment] 2017-03-08 16:43
This is a dupe of #1377.

**Comment by lamont-granquist** [comment] 2018-03-21 17:31
closing as dup

**Closed by lamont-granquist** 2018-03-21 17:31 UTC
